/*
 * GENERATED by scripts/fonts/generate-preload-list.mjs — do not hand-edit (#740).
 *
 * The faces next/font marked preloadable (the `.p` in each filename), imported so the
 * bundler resolves the content hash it adds at build time. A literal path here would be
 * stale the moment a font changed.
 *
 * Regenerate after re-vendoring:  node scripts/fonts/generate-preload-list.mjs
 */
import face0 from '../fonts/1a4aa50920b5315c-s.p.woff2';
import face1 from '../fonts/26d4368bf94c0ec4-s.p.woff2';
import face2 from '../fonts/558ca1a6aa3cb55e-s.p.woff2';
import face3 from '../fonts/982ceffe7b733b3b-s.p.woff2';
import face4 from '../fonts/98e207f02528a563-s.p.woff2';
import face5 from '../fonts/d3ebbfd689654d3a-s.p.woff2';
import face6 from '../fonts/db96af6b531dc71f-s.p.woff2';
import face7 from '../fonts/e210f091ebfac73b-s.p.woff2';

/** Rendered as <link rel="preload" as="font" crossorigin> by src/app/layout.tsx. */
export const PRELOAD_FONTS: readonly string[] = [
  face0,
  face1,
  face2,
  face3,
  face4,
  face5,
  face6,
  face7,
];
