import { readdirSync, existsSync } from 'node:fs';
import { join } from 'node:path';

/**
 * How many wireframes this project has, counted from the committed tree.
 *
 * SERVER/BUILD ONLY — this reads the filesystem, so it must never be pulled
 * into a client bundle. It is imported by the landing page, which is a server
 * component, and by its test.
 *
 * The obvious source is `public/wireframes/wireframes-manifest.json`, and the
 * first version of #408 used it. That file is **generated by `prebuild`
 * (`scripts/sync-wireframes.sh`) and gitignored**, so it exists locally and
 * not in a fresh checkout: `tsc --noEmit` resolved the import here and failed
 * in CI, which is the "CI builds the committed tree only" trap.
 *
 * So the count comes from what `sync-wireframes.sh` itself calls the canonical
 * source — `features/<category>/<feature>/wireframes/*.svg`. Top level only:
 * `includes/` holds shared chrome (135 partials at the time of writing) that
 * the viewer never lists as a wireframe, and counting those would overstate
 * the number roughly fourfold.
 */
const FEATURES_DIR = 'features';

export function countWireframes(root: string = process.cwd()): number {
  const base = join(root, FEATURES_DIR);
  if (!existsSync(base)) return 0;

  let total = 0;
  for (const category of readdirSync(base, { withFileTypes: true })) {
    if (!category.isDirectory()) continue;
    const categoryDir = join(base, category.name);

    for (const feature of readdirSync(categoryDir, { withFileTypes: true })) {
      if (!feature.isDirectory()) continue;
      const wireframeDir = join(categoryDir, feature.name, 'wireframes');
      if (!existsSync(wireframeDir)) continue;

      // Files only — this is what skips `includes/`.
      total += readdirSync(wireframeDir, { withFileTypes: true }).filter(
        (entry) => entry.isFile() && entry.name.endsWith('.svg')
      ).length;
    }
  }
  return total;
}
