#!/usr/bin/env bash
# Live-acceptance E2E runner — drives the payment specs against the REAL
# provider sandboxes (Stripe test mode / PayPal sandbox) using the creds in
# your gitignored .env. CI never runs these legs (its env carries no provider
# keys, so the specs auto-skip); this script is how they actually get run.
#
# Run from the HOST (it orchestrates docker compose):
#   pnpm run test:e2e:live                       # default: payment suite, chromium
#   ./scripts/e2e-live-acceptance.sh tests/e2e/payment/08-subscription-lifecycle.spec.ts --project=chromium-gen
#
# What it encodes (each step failed with a misleading symptom before it was
# understood — see docs/project/TESTING.md "Live-acceptance E2E"):
#   1. ROOT-PATH build: CI has no .env, so its build has no basePath. A
#      basePath build under plain `serve` 404s every chunk → blank page.
#   2. Serve on :3001: the edge fns' CORS allowlists ONLY the configured
#      site URL + localhost:3000/3001 — any other port → "Failed to fetch".
#   3. NEXT_PUBLIC_BASE_PATH= on the TEST RUN too: playwright's dotenv loads
#      the /ScriptHammer value from .env and the authed fixture helpers
#      prepend it to gotos → app-styled 404s on a root-path build.
#   4. The build runs in the `builder` SERVICE, never in the dev container
#      (#293, #508). See the header of step 1.
set -euo pipefail
cd "$(dirname "$0")/.."

# Host guard: inside the container there is no docker CLI — without this the
# script dies at the first compose call with a confusing error.
if ! command -v docker >/dev/null 2>&1; then
  echo "error: run this from the HOST (it orchestrates docker compose);" >&2
  echo "       inside the container use plain 'pnpm exec playwright test'." >&2
  exit 1
fi

ARGS=("$@")
if [ ${#ARGS[@]} -eq 0 ]; then
  ARGS=(tests/e2e/payment --project=chromium-gen)
fi

# ── What this run leaves behind on the SHARED BIND MOUNT, and how it is undone.
#
# Moving the build into its own container (step 1) isolates .next. It does NOT
# isolate the repo, which both containers mount, and `prebuild` writes into it.
# Two of those writes matter because they are ROOT-PATH values that outlive the
# run and the dev server is watching them:
#
#   public/manifest.json                 tracked   — start_url/scope flip to /
#   src/config/project-detected.{json,ts} ignored  — basePath flips to ""
#
# The manifest is restorable with git. The project-detected pair is gitignored
# (generated by scripts/detect-project.js), so `git checkout` cannot bring it
# back — snapshot the bytes instead and copy them over at exit. Leaving them at
# basePath "" makes the running dev server recompile into a rootless app while
# .env still says /ScriptHammer, which reads as "the dev server broke".
MANIFEST_CLEAN_AT_START=0
git diff --quiet -- public/manifest.json 2>/dev/null && MANIFEST_CLEAN_AT_START=1

DETECTED_FILES="src/config/project-detected.json src/config/project-detected.ts"
SNAPSHOT_DIR="$(mktemp -d)"
# Absent files are normal, not an error: on a fresh checkout detect-project.js
# has not run yet, so there is nothing to snapshot and nothing to restore.
for f in $DETECTED_FILES; do
  if [ -f "$f" ]; then
    cp "$f" "$SNAPSHOT_DIR/$(basename "$f")"
  fi
done

# Matches both the npx and pnpm-exec forms of the serve process (whose
# cmdline is node .../serve/build/main.js out -l 3001 — no literal "serve out").
kill_serve() {
  docker compose exec -T scripthammer pkill -f "serve.*-l 3001" >/dev/null 2>&1 || true
}

cleanup() {
  kill_serve
  # Root-path builds flip start_url/scope in the generated manifest.
  if [ "$MANIFEST_CLEAN_AT_START" -eq 1 ]; then
    git checkout -- public/manifest.json 2>/dev/null || true
  fi
  for f in $DETECTED_FILES; do
    snap="$SNAPSHOT_DIR/$(basename "$f")"
    if [ -f "$snap" ]; then
      cp "$snap" "$f"
    fi
  done
  rm -rf "$SNAPSHOT_DIR"
}
trap cleanup EXIT

echo "== 1/3 clean root-path build (CI-matching), in the builder container"
# THE BUILD RUNS IN ITS OWN CONTAINER (#293, #508), and that is the whole fix.
#
# It used to run in the dev container with NEXT_DIST_DIR=.next-acceptance/build
# — an isolated distDir on a named volume, which sounds sufficient and was not:
# a build racing the live `next dev` still died at "Collecting page data" with
#
#     unhandledRejection Error: Cannot find module './6048.js'
#
# six times across 2026-08-02/03, three of them killing an acceptance run
# mid-session. Exit 1 with no test output reads exactly like a real build break.
#
# `builder` (docker-compose.yml) is the same image with its OWN .next volume and
# no dev server inside it, so there is no shared distDir to race and nothing to
# thread through call sites. With the DEFAULT distDir the export lands in ./out
# on the bind mount, which is what CI serves too (`serve out -l 3000`) — so this
# step is now closer to CI-matching, not further, and the .next-acceptance
# volume is gone.
#
# NEXT_PUBLIC_BASE_PATH= (empty) still produces a ROOT build: detect-project.js
# only auto-derives /RepoName under GITHUB_ACTIONS, which is unset here.
BUILD_LOG="$SNAPSHOT_DIR/build.log"
build_once() {
  docker compose run --rm -e NEXT_PUBLIC_BASE_PATH= builder \
    sh -c 'rm -rf out && pnpm run build' 2>&1 | tee "$BUILD_LOG"
  return "${PIPESTATUS[0]}"
}

# The corruption signature, kept as a BACKSTOP for whatever the container split
# misses. Without it a recurrence is a bare exit 1 that costs a diagnosis every
# time; with it the run says what happened and retries once. Twice is a real
# break — never loop on it.
CORRUPTION_RE="Cannot find module '\./[0-9]+\.js'|Cannot find module for page"
if ! build_once; then
  if grep -Eq "$CORRUPTION_RE" "$BUILD_LOG"; then
    echo "" >&2
    echo "!! build hit the #508 .next-corruption signature, not a code break:" >&2
    grep -Eo "$CORRUPTION_RE" "$BUILD_LOG" | sort -u | sed 's/^/     /' >&2
    echo "!! retrying once. If this repeats, something IS sharing state with" >&2
    echo "   the dev server again — check scripts/ for a build outside 'builder'." >&2
    echo "" >&2
    if ! build_once; then
      echo "!! second attempt failed too — treating this as a REAL build failure." >&2
      exit 1
    fi
  else
    exit 1
  fi
fi

echo "== 2/3 static serve on :3001"
# Clear any orphan from a previous crashed run FIRST — otherwise the health
# check below can green-light a stale server still holding the old build.
kill_serve
# pnpm exec (local devDependency), NOT npx: on a freshly created container the
# npm cache is empty and npx's download can outlast any reasonable wait.
#
# `out` — the ordinary export directory, on the bind mount, exactly what CI
# serves. Step 1 used to hand back a custom distDir instead (Next 15.5 replaces
# a custom distDir's contents with the finished site and never creates out/),
# which was a consequence of building in the dev container, not a requirement.
# Assert it exists before serving: `serve` happily starts on a missing directory
# and every request then 404s, which reads as an app failure rather than a
# missing build.
docker compose exec -T scripthammer sh -c '[ -f out/index.html ]' || {
  echo "build produced no out/index.html — step 1 did not export" >&2
  exit 1
}
docker compose exec -T -d scripthammer pnpm exec serve out -l 3001
for i in $(seq 1 30); do
  if docker compose exec -T scripthammer sh -c 'curl -sf -o /dev/null http://localhost:3001/'; then
    break
  fi
  [ "$i" -eq 30 ] && { echo "serve never came up on :3001" >&2; exit 1; }
  sleep 1
done

echo "== 3/3 playwright: ${ARGS[*]}"
# --reporter=list comes FIRST so an operator-supplied --reporter in ARGS wins
# (playwright takes the last occurrence of a single-value option).
docker compose exec -T \
  -e PLAYWRIGHT_BROWSERS_PATH=/ms-playwright \
  -e SKIP_WEBSERVER=1 \
  -e BASE_URL=http://localhost:3001 \
  -e NEXT_PUBLIC_BASE_PATH= \
  scripthammer pnpm exec playwright test --reporter=list "${ARGS[@]}"

echo "== done — read the per-test PASS/SKIP lines above; a live test that"
echo "   SKIPPED means a cred is missing from .env, not that it passed."
